"""empty message

Revision ID: 0b9cd7437cf4
Revises: 869400044850
Create Date: 2024-03-12 14:27:49.408734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9cd7437cf4'
down_revision = '869400044850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
