"""empty message

Revision ID: 6d784c2b93dc
Revises: 8686cef1ad94
Create Date: 2024-10-15 16:24:56.185369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d784c2b93dc'
down_revision = '8686cef1ad94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('query_hash', sa.String(length=32), nullable=False),
    sa.Column('is_scheduled_query', sa.Boolean(), nullable=False),
    sa.Column('is_api_user', sa.Boolean(), nullable=False),
    sa.Column('size', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.Column('runtime', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('execution_successful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_executions_data_source_id'), 'query_executions', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_query_executions_query_id'), 'query_executions', ['query_id'], unique=False)
    op.create_index(op.f('ix_query_executions_user_id'), 'query_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_executions_user_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_query_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_data_source_id'), table_name='query_executions')
    op.drop_table('query_executions')
    # ### end Alembic commands ###
