"""empty message

Revision ID: 8686cef1ad94
Revises: 869400044850
Create Date: 2024-03-13 17:49:07.403840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8686cef1ad94'
down_revision = '869400044850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('max_cache_time', postgresql.DOUBLE_PRECISION(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'max_cache_time')
    # ### end Alembic commands ###
