"""empty message

Revision ID: 869400044850
Revises: 8d48f615c497
Create Date: 2023-11-24 19:32:45.876366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869400044850'
down_revision = '8d48f615c497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('allowed_executions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'allowed_executions')
    # ### end Alembic commands ###
