"""empty message

Revision ID: 8d48f615c497
Revises: 89bc7873a3e0
Create Date: 2023-11-22 22:21:21.366662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d48f615c497'
down_revision = '89bc7873a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_executions_dashboard_id'), 'dashboard_executions', ['dashboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_executions_dashboard_id'), table_name='dashboard_executions')
    op.drop_table('dashboard_executions')
    # ### end Alembic commands ###
