"""empty message

Revision ID: ca17a97ac44e
Revises: 6d784c2b93dc
Create Date: 2024-10-17 15:43:47.721259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca17a97ac44e'
down_revision = '6d784c2b93dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_query_executions_creation_date'), 'query_executions', ['creation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_executions_creation_date'), table_name='query_executions')
    # ### end Alembic commands ###
