#!/bin/bash
BUILD=$(echo $PipelineExecutionId | cut -c1-8)

sed -ri 's/^__version__ = "dev"/__version__ = '\""$TAG_DOCKER"\"'/' __init__.py
sed -i "s/dev/$BUILD/" client/app/version.json
sed -i "s/__version__/$TAG/" package.json
